// Generated by CoffeeScript 1.8.0
var h, halfh, halfw, margin, totalh, totalw, w, ngroup, group;

h = 600;

w = 800;


margin = {
  left: 60,
  top: 40,
  right: 40,
  bottom: 40,
  inner: 5
};

halfh = h + margin.top + margin.bottom;

totalh = halfh * 2;

halfw = w + margin.left + margin.right;

totalw = halfw * 2;



ngroup = 12;
group = (function() {
  var _i, _len, _results;
  _results = [];
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    grpNum = data[_i][6]; //6th value is group
    _results.push(grpNum);
  }
  return _results;
})();

var mychart;
mychart = scatterplot()
  .xlab("")
  .ylab("")
  .xlim([18,0])
  .ylim([0,15])
  .height(h)
  .width(w)
  .margin(margin)
  .rectcolor("rgba(0,0,0,0)")
  .pointstroke("black")
  .nxticks(0)
  .nyticks(0)
  .margin({left:60, top:0, right:40, bottom:40, inner:5}) ;
  
d3.select("div#chart1").datum({
  data: data,
  group: group
}).call(mychart);
mychart.pointsSelect().on("mouseover", function(d) {
  return d3.select(this).attr("r", mychart.pointsize() * 3);
}).on("mouseout", function(d) {
  return d3.select(this).attr("r", mychart.pointsize());
}).on("click", function(d) {
  var row = data[d];
  var name = row[3];
  var district = row[4];
  var party = row[5];
  var age = row[7];
  var www = row[9];
  var education = row[12];
  
  var q1 = row[13];
  var q2 = row[14];
  var q3 = row[15];
  var q4 = row[16];
  var q5 = row[17];
  var q6 = row[18];
  var q7 = row[19];
  var q8 = row[20];
  var q9 = row[21];
  var q10 = row[22];
  var q11 = row[23];
  var q12 = row[24];
  var q13 = row[25];
  var q14 = row[26];
  var q15 = row[27];
  var q16 = row[28];
  var q17 = row[29];
  var q18 = row[30];
  var q19 = row[31];
  var q20 = row[32];
  var q21 = row[33];
  var q22 = row[34];
  var q23 = row[35];
  var q24 = row[36];
  var q25 = row[37];
  var q26 = row[38];
  var q27 = row[39];
  var q28 = row[40];
  var q29 = row[41];
  var q30 = row[42];


  $("#details-pane #name").html(name);
  $("#details-pane #district").html(district);
  $("#details-pane #party").html(party);
  $("#details-pane #age").html(age);
  $("#details-pane #www").attr("href", www).html(www);
  $("#details-pane #education").html(education);
  
  $('#details-pane #q1').html(q1);
  $('#details-pane #q2').html(q2);
  $('#details-pane #q3').html(q3);
  $('#details-pane #q4').html(q4);
  $('#details-pane #q5').html(q5);
  $('#details-pane #q6').html(q6);
  $('#details-pane #q7').html(q7);
  $('#details-pane #q8').html(q8);
  $('#details-pane #q9').html(q9);
  $('#details-pane #q10').html(q10);
  $('#details-pane #q11').html(q11);
  $('#details-pane #q12').html(q12);
  $('#details-pane #q13').html(q13);
  $('#details-pane #q14').html(q14);
  $('#details-pane #q15').html(q15);
  $('#details-pane #q16').html(q16);
  $('#details-pane #q17').html(q17);
  $('#details-pane #q18').html(q18);
  $('#details-pane #q19').html(q19);
  $('#details-pane #q20').html(q20);
  $('#details-pane #q21').html(q21);
  $('#details-pane #q22').html(q22);
  $('#details-pane #q23').html(q23);
  $('#details-pane #q24').html(q24);
  $('#details-pane #q25').html(q25);
  $('#details-pane #q26').html(q26);
  $('#details-pane #q27').html(q27);
  $('#details-pane #q28').html(q28);
  $('#details-pane #q29').html(q29);
  $('#details-pane #q30').html(q30);
});



$(document).ready(function(){
	$("#candidate-filter").keyup(function(e) {
  $("#points circle").attr("r", 3);
    var qry=$(this).val();
    if(qry.length>2){
      for(var i=0;i<data.length;i++){
        //Check if name contains query string
        if(data[i][3].toLowerCase().indexOf(qry) >= 0){
          $("circle.pt"+i).attr("r", 10);
        }
      }
    }
  });
});

